PARAMS:
  LOSS: categorical_crossentropy
  METRICS: accuracy
  OPTIMIZER: adam
  EPOCHS: 20
  BATCH_SIZE: 32

VGG16_PAR:
  IMG_WIDTH: 256
  IMG_HEIGHT: 256
  TRAINABLE : FALSE

IMAGE_DIR:
  TRAIN_DIR: documents/train
  VALIDATION_DIR: documents/validation  

IMAGE_PREPROCESS:
  SHEAR_RANGE: 0.2
  ZOOM_RANGE: 0.2
  TARGET_SIZE: 256
  BATCH_SIZE : 20


artifacts:
  artifacts_dir: artifacts
  model_dir: model
  model_name: model.h5
  CHECKPOINT_DIR: checkpoints
    

EMAIL:
 USER: rohit050695@gmail.com
 PWD: bjkoxaaujyloxeic
 FROM: rohit050695@gmail.com
 SUBJECT: DOCUMENTS FOR PROCESSING
 TEXT_MESSAGE: Please find attached the zip file

 
 logs:
  logs_dir: logs_dir
  general_logs: general_logs

CALLBACKS:
  patience: 5
  restore_best_weights: True

